Adicionado botão para iniciar a corrida e roleta russa (falcao-g#23)
falcao-g/Falbot pull request #29
Opened 2023-06-13 06:38 UTC by Vicarillous

Agora o criador da corrida/roleta tem um botão que o permite iniciar os jogos antes do timer de 1 minutos.

![skipFalbot](https://github.com/falcao-g/Falbot/assets/56037523/bd47a7ab-95d9-467e-ab15-8b9f606b90bc)

2023-06-14 01:28 UTC, falcao-g requested changes
muito obrigado vica, só deixei algumas observações

2023-06-14 01:28 UTC, falcao-g commented on src/utils/functions.js
única mudança que eu gostaria seria outro emoji, talvez esse ▶️, seja bom

2023-06-14 01:28 UTC, falcao-g commented on src/commands/russianroulette.js
mesma coisa aqui, só faltou a checagem do accept

2023-06-14 01:28 UTC, falcao-g commented on src/commands/horseduel.js
você checou pra ver se a interação tinha o id "skip", na parte do skip mas esqueceu de checar de novo pro "accept"

2023-06-14 02:11 UTC, Vicarillous commented
Realizei as alterações conforme solicitado

2023-06-14 18:11 UTC, falcao-g approved these changes
closes #23 

parece bom, obrigado pela ajuda

2023-06-14 18:12 UTC, merged

2023-12-18 04:13 UTC, falcao-g commented
@all-contributors please add @Vinicius-Marques6 for code